# Generated by Django 5.0.5 on 2024-05-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_item_todolist_remove_item_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="click_count",
            field=models.IntegerField(default=0),
        ),
    ]
