# Generated by Django 5.0.5 on 2024-05-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_item_click_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="c1_color",
            field=models.CharField(default="white", max_length=20),
        ),
        migrations.AlterField(
            model_name="item",
            name="c2_color",
            field=models.CharField(default="white", max_length=20),
        ),
        migrations.AlterField(
            model_name="item",
            name="c3_color",
            field=models.CharField(default="white", max_length=20),
        ),
    ]
