# Generated by Django 5.0.5 on 2024-05-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_item_c1_color_alter_item_c2_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="c1_active",
        ),
        migrations.RemoveField(
            model_name="item",
            name="c2_active",
        ),
        migrations.RemoveField(
            model_name="item",
            name="c3_active",
        ),
    ]
